### ISSUE TITLE
Trying to use project in 3.2.3

### ISSUE THREAD

**Issue by salvafide** [Lamelynx/GodotGetImagePlugin-Android#1]
Hi, I would love to be able to use the feature of this plugin, (picking a file from the gallery etc), but I am having trouble. I havent used a plugin for Godot before so I am unsure if I am doing it right. Would love some help if you were to see this thanks. Before trying to export with custom template I had it working to export to android. I tried following the steps I could find to do a custom export. Godot stops responding when I try to export so I do not know what the errors could be.

**Comment by salvafide** [comment]
Got it working, great plugin btw, very helpful

**Comment by Lamelynx** [comment]
Hi and thanks.
Glad someone appreciates my efforts :-) .
What was wrong, did you have to generate a new release for 3.2.3 or some error with the plugin?

**Comment by salvafide** [comment]
Ya, definitely appreciated XD.
Im not 100% sure what fixed it but i went through the documentation to make sure I had everything, which I did,(downloaded the newest java jdk anyways) but I think what got it working was building with custom template checked without the plugin checked. Then build with the plugin checked. I think it may have been trying to complie too many things at once with both at the same time?

**Comment by salvafide** [comment]
Also as someone who just experience trying to add your plugin as a newbie, I think it would be helpful to explain a little more what files you need from the .zip to get it working. After getting the example project running I was confused about what to do with that second folder in the zip.("GodotGetImagePlugin") I ended up just copying the aar and gdap from the example folder into my project + ur main(gd, tscn) to make sure my project would build with the plugin working.

**Comment by Lamelynx** [comment]
You cloned the whole project? 
You should have unziped the zip from release folder.
GodotGetImagePlugin is used if you wish to generate a new .aar from scratch. 
I made a release for Godot 3.2.3 but have not tested it yet. look in the release folder for the zip.

**Comment by salvafide** [comment]
I see it
