### ISSUE TITLE
App crashes 

### ISSUE THREAD

**Issue by Swaraj-cs** [Lamelynx/GodotGetImagePlugin-Android#10]
Hi, app crashes in while opening with custom build and "Godot Get Image" is enabled from plugin. Without that, the app working.

**Comment by Lamelynx** [comment]
Which version of Godot and GodotGetImagePlugin-Android are you using?
Have you checked if any errors shows in ADB?

**Comment by Swaraj-cs** [comment]
Thank you for responding to the issue,

Am using Godot version 3.3.2 and godotgetimageplugin_v0.1.4_for_godot_3.3.2.
Not receiving any error, "name has stopped.. open app again". When build without enabling plugin, its working.

**Comment by Lamelynx** [comment]
Have you tried to build the [GodotExample](https://github.com/Lamelynx/GodotGetImagePlugin-Android/tree/master/GodotExample)?

**Comment by Swaraj-cs** [comment]
Yes, that is working.

**Comment by Swaraj-cs** [comment]
Thank you .. understood.. seems it was an issue with other plugins used.. Sorry for the trouble.

**Comment by Lamelynx** [comment]
No problem 👍
