### ISSUE TITLE
camera orientation and setting front/back camera

### ISSUE THREAD

**Issue by Swaraj-cs** [Lamelynx/GodotGetImagePlugin-Android#12]
Hi, is there any fix for this? In some devices its not working.

**Comment by Lamelynx** [comment]
Do you know which devices are not working?

Both camera orientation and setting front camera is highly manufacture dependent.
The solution in this plugin works on most devices but not all.

To solve the problem with setting front for some devices [this part](https://github.com/Lamelynx/GodotGetImagePlugin-Android/blob/49cc8da0e6410ea20d6aa680905567c04c8a7d8f/GodotGetImagePlugin/godotgetimage/src/main/java/com/gmail/lamelynx/godotgetimage/GodotGetImage.kt#L204-L229) needs to be updated.

To fix camera orientation, this function: [rotateImageIfRequired()](https://github.com/Lamelynx/GodotGetImagePlugin-Android/blob/49cc8da0e6410ea20d6aa680905567c04c8a7d8f/GodotGetImagePlugin/godotgetimage/src/main/java/com/gmail/lamelynx/godotgetimage/GodotGetImage.kt#L512-L537) needs to be updated with the problematic devices.

You are welcome to try to solve this if you think you can.

**Comment by Swaraj-cs** [comment]
Hi, 
 I was trying in moto g71 and samsung m42. In some other devices also its doing the same. In same devices, even if we are trying to set to front camera, its not setting . 
 
 It will be a great help if you could update it.

**Comment by Swaraj-cs** [comment]
Hi, is there a fix to this? also cant fix to portrait view.

**Comment by Lamelynx** [comment]
I have not found any solution to this problem. I would suggest to add a rotation button so the user can rotate the image to correct orientation.
