### ISSUE TITLE
Issues with godot 4

### ISSUE THREAD

**Issue by MetSpek** [Lamelynx/GodotGetImagePlugin-Android#14]
I've been trying to generate the .aar file for godot 4 but the 'gradlew.bat assembleRelease' command does not work anymore even after update every dependency. I saw that you need the applicationId "com.gmail.lamelynx.godotgetimageplugin" and I think the problem lies there cause I don't know what else it should be.

**Comment by MetSpek** [comment]
Somehow I got the 3.4.4 version working, only now only when I take a picture or try to add an image from the gallery the app crashes, even when I do absolutely nothing with the image.

**Comment by Lamelynx** [comment]
I manage to generate a new release and updated the example project to Godot 4, it's tested on my device and is working as expected.
Please let me know if the release work for you.

**Comment by MetSpek** [comment]
It does! Thank you so much :D you saved my assignment
