### ISSUE TITLE
Android 13

### ISSUE THREAD

**Issue by MingTsv** [Lamelynx/GodotGetImagePlugin-Android#15]
it doesn't work on android 13

**Comment by finepointcgi** [comment]
I just tested this on android 13 with a google pixel 5 it seems to work for me. 
What error are you getting?

Edit: It does seem to be broken it looks like godot is not requesting the android.permission.READ_EXTERNAL_STORAGE which seems to be a godot bug.

**Comment by MingTsv** [comment]
i have given READ_EXTERNAL_STORAGE, WRITE_EXTERNAL_STORAGE and MANAGE_EXTERNAL_STORAGE permission to my game but when I click the button to run getGalleyImage() it doesn't show anything.  I'm using godot 3.5 and your 3.4 plugin

**Comment by Lamelynx** [comment]
For best compatibility, you need to have the same vesion on the plugin as the version on Godot.

**Comment by MingTsv** [comment]
I can't find my version in your plugin

**Comment by finepointcgi** [comment]
> For best compatibility, you need to have the same vesion on the plugin as the version on Godot.

I pulled the 4.0.3 aab updated the api to 31 build tools are now 30 and updated kotlin to 1.6.0. I don't think its the plugin I think its Godot itself.
See: 
https://github.com/godotengine/godot/issues/60635

**Comment by MingTsv** [comment]
> > Để tương thích tốt nhất, bạn cần có cùng phiên bản trên plugin với phiên bản trên Godot.
> 
> Tôi đã kéo aab 4.0.3 đã cập nhật api lên 31 công cụ xây dựng hiện là 30 và cập nhật kotlin lên 1.6.0. Tôi không nghĩ đó là plugin mà tôi nghĩ đó là Godot. Xem: [godotengine/godot#60635](https://github.com/godotengine/godot/issues/60635)

Did you fix it yet?  Please help me if you have a solution to this problem

**Comment by ghost** [comment]
I think this is related to API changes in Android 13. Apparently `android.permission.READ_EXTERNAL_STORAGE ` was split into multiple different permissions.
https://developer.android.com/about/versions/14/changes/partial-photo-video-access
I have tried granting my app `android.permission.READ_MEDIA_IMAGES` with a custom permission in Godot, but `getGalleryImages()` still fails to bring up the image selection interface.

**Comment by Lamelynx** [comment]
I'm looking into implentering [Photo picker](https://developer.android.com/training/data-storage/shared/photopicker) , it might fix the problem.

**Comment by ghost** [comment]
I was able to implement photo picker in Android (including 13) with the following code:

```
	public void getGalleryImage() {
		Log.d("godot", "Call - getGalleryImage");
		Intent intent = new Intent(Intent.ACTION_PICK);
		intent.setType("image/*");
		startActivityForResult(getActivity(), intent, 101, null);
	}

	public void onMainActivityResult(int requestCode, int resultCode, Intent data) {
		if (resultCode == RESULT_OK) {
			// Get the URI of the selected media file
			Uri imageUri = data.getData();
			Bitmap bitmap;
			try {
				InputStream imageStream = getGodot().getContext().getContentResolver().openInputStream(imageUri);
				bitmap = BitmapFactory.decodeStream(imageStream);
				imageStream.close();
			} catch (FileNotFoundException e) {
				throw new RuntimeException(e);
			} catch (IOException e) {
				throw new RuntimeException(e);
			}
			Dictionary imageDict = new Dictionary();
			ByteArrayOutputStream stream = new ByteArrayOutputStream();
			bitmap.compress(Bitmap.CompressFormat.JPEG, 90, stream);
			try {
				stream.close();
			} catch (IOException e) {
				throw new RuntimeException(e);
			}
			imageDict.put("0", stream.toByteArray());
			emitSignal("image_request_completed", imageDict);
		}
	}

	@NonNull
	@Override
	public Set<SignalInfo> getPluginSignals() {
		Set<SignalInfo> signals = new ArraySet<>();
		signals.add(new SignalInfo("image_request_completed", Dictionary.class));
		return signals;
	}
```

It should work as a drop in replacement for single images. I haven't implemented multiple selection because my app does not require it.

**Comment by Lamelynx** [comment]
Thanks for sharing @blurrred :-)

**Comment by blurrred** [comment]
No problem. I forgot there was another class that I had to make in order to get it to work.

I just called it 'PhotoPicker.java' and put it in the same folder as the Godot plugin.

```
public class PhotoPicker extends Fragment {
	public PhotoPicker() {
		// Required empty public constructor
	}

	public static PhotoPicker newInstance() {
		PhotoPicker fragment = new PhotoPicker();
		return fragment;
	}

	@Override
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		ActivityResultLauncher<PickVisualMediaRequest> pickMedia =
				registerForActivityResult(new ActivityResultContracts.PickVisualMedia(), uri -> {
					// Callback is invoked after the user selects a media item or closes the
					// photo picker.
					if (uri != null) {
						Log.d("PhotoPicker", "Selected URI: " + uri);
					} else {
						Log.d("PhotoPicker", "No media selected");
					}
				});

		pickMedia.launch(new PickVisualMediaRequest.Builder()
				.setMediaType(ActivityResultContracts.PickVisualMedia.ImageOnly.INSTANCE)
				.build());
	}
```

**Comment by blurrred** [comment]
Hey so, I don't think the latter comment is necessary. I added it because it's what the documentation said, but upon further testing, *it really looks* like we only need the `Intent intent = new Intent(Intent.ACTION_PICK);`
I was kind of excited because it all worked, but if you're having difficulty integrating it, just disregard that last part.

**Comment by Ayomideabdulazeez** [comment]
> I'm looking into implentering [Photo picker](https://developer.android.com/training/data-storage/shared/photopicker) , it might fix the problem.

Hello have you been able to implement it ?

**Comment by Lamelynx** [comment]
Unfortunately, I haven't taken the time for that yet.

**Comment by Ayomideabdulazeez** [comment]
> Unfortunately, I haven't taken the time for that yet.

Okay, but would i be able to implement it myself into your plugin, i think it's the GodotGetImage.kt i need to alter right ?

**Comment by Ayomideabdulazeez** [comment]
So good news, i've been able to get it working with android 13, by checking the android version, and then applying the new persmissions required, so basically if the android version is 13 we use  Manifest.permission.READ_MEDIA_IMAGES else we then use the Manifest.permission.READ_EXTERNAL_STORAGE![Capture](https://github.com/Lamelynx/GodotGetImagePlugin-Android/assets/109722734/5515c520-44cb-4ef1-848a-464be07df810)

**Comment by Ayomideabdulazeez** [comment]
@Lamelynx if you want i could create a pull request ?

**Comment by Lamelynx** [comment]
Great work and please do a pull request. I will test it in my setup.

**Comment by Ayomideabdulazeez** [comment]
> Great work and please do a pull request. I will test it in my setup.

Sure, I'll do that in my free-time

**Comment by Ayomideabdulazeez** [comment]
> No problem. I forgot there was another class that I had to make in order to get it to work.
> 
> I just called it 'PhotoPicker.java' and put it in the same folder as the Godot plugin.
> 
> ```
> public class PhotoPicker extends Fragment {
> 	public PhotoPicker() {
> 		// Required empty public constructor
> 	}
> 
> 	public static PhotoPicker newInstance() {
> 		PhotoPicker fragment = new PhotoPicker();
> 		return fragment;
> 	}
> 
> 	@Override
> 	public void onCreate(Bundle savedInstanceState) {
> 		super.onCreate(savedInstanceState);
> 		ActivityResultLauncher<PickVisualMediaRequest> pickMedia =
> 				registerForActivityResult(new ActivityResultContracts.PickVisualMedia(), uri -> {
> 					// Callback is invoked after the user selects a media item or closes the
> 					// photo picker.
> 					if (uri != null) {
> 						Log.d("PhotoPicker", "Selected URI: " + uri);
> 					} else {
> 						Log.d("PhotoPicker", "No media selected");
> 					}
> 				});
> 
> 		pickMedia.launch(new PickVisualMediaRequest.Builder()
> 				.setMediaType(ActivityResultContracts.PickVisualMedia.ImageOnly.INSTANCE)
> 				.build());
> 	}
> ```

Can you please explain a bit how this can be implemented ?

**Comment by yan88a** [comment]
Hey guys
any breakthroughs here with godot 4 and android 13?

**Comment by Lamelynx** [comment]
I have not yet successfully implement PhotoPicker but done a update based on [Ayomideabdulazeez](https://github.com/Ayomideabdulazeez) solution.
I have not tested it on a Android 13 device tough.

**Comment by yan88a** [comment]
thanks @Lamelynx ! - did a quick check - looks like it works on my s21 (android 13)
i was able to make it work via @blurrred solution as well..

**Comment by yan88a** [comment]
well, was happy to see the photo gallery is opened with both versions so assumed all works fine.
however - couldnt retrieve the "image_request_completed" signal in both options via the "get image"/"get images"

probably some permissions issue i overlooked?

**Comment by Lamelynx** [comment]
Do you have android.permission.READ_MEDIA_IMAGES?

**Comment by yan88a** [comment]
Yep
added it to the project's manifest...
same result

after poking logcat for a bit - seems the signal is not fired

**Comment by yan88a** [comment]
Sorry for taking that long.
Seems that on android 13 "onMainActivityResult" is deprecated. 
therefore - "image_request_completed" signal is not fired 
 (still couldnt get it to work)

**Comment by Lamelynx** [comment]
We need to revise how the plugin i handling the activity then.

I have problems to implement PhotoPicker, I got class not found error even tough I implement "androidx.activity:activity-ktx:1.8.0-rc01" in the plugin. Everything is compiling but don't run on the device.
Can you run this code, (I just got NoClassError for class isPhotoPickerAvailable()):

`if (godot.context?.let { isPhotoPickerAvailable(it) } == true) {
            Log.d(TAG, "PhotoPicker is available on this device")
}`

**Comment by yan88a** [comment]
sure thing
i implemented the"androidx.activity:activity:1.7.2"
photo picker works ok and opens on android prior to 13 - went with @blurrred  implementation..
debug'd it a bit more - and the signal is not shooting - even though "onMainActivityResult" is called.
looks like the resultCode returns as "0"

still trying to figure out what that means

**Comment by yan88a** [comment]
@Lamelynx - same for me.
couldnt find the class for -
Boolean isAvilble = .isPhotoPickerAvailable(getGodot().getContext());

wired..

**Comment by yan88a** [comment]
@Lamelynx  got it to work on android 13 and lower (11)
went with @blurrred solution and changed the intent action from "get image" to "action get content)
`public void getGalleryImage() {
        PhotoPicker PhotoPicker = new PhotoPicker();
        Log.d("godot", "Call - getGalleryImage");
        //Intent intent = new Intent(Intent.ACTION_PICK);
        Intent intent = new Intent();
        intent.setAction(Intent.ACTION_GET_CONTENT);
        intent.setType("image/*");
        //activityResultLauncher.launch(intent);
        startActivityForResult(getActivity(), intent, 101, null);

    }

    @Override
    public void onMainActivityResult(int requestCode, int resultCode, Intent data) {
        Log.d("godot","result is "+ resultCode);
        if (resultCode == RESULT_OK) {
            // Get the URI of the selected media file
            Uri imageUri = data.getData();
            Bitmap bitmap;
            try {
                InputStream imageStream = getGodot().getContext().getContentResolver().openInputStream(imageUri);
                bitmap = BitmapFactory.decodeStream(imageStream);
                imageStream.close();
            } catch (FileNotFoundException e) {
                throw new RuntimeException(e);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
            Dictionary imageDict = new Dictionary();
            ByteArrayOutputStream stream = new ByteArrayOutputStream();
            bitmap.compress(Bitmap.CompressFormat.JPEG, 90, stream);
            try {
                stream.close();
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
            imageDict.put("0", stream.toByteArray());
            Log.d("godot","fired signal");
            emitSignal("image_request_completed", imageDict);
        }
    }`

painful.

**Comment by bouncymarble** [comment]
Hi @yan88a @Ayomideabdulazeez @blurrred , could you guys please share an .aar file that works in godot 3.5.3? I've tried to generate it myself with the solutions you provided but always get a gradle error. I'd really appreciate it, thanks.

**Comment by yan88a** [comment]
sure @bouncymarble 
[aarForImage.zip](https://github.com/Lamelynx/GodotGetImagePlugin-Android/files/12812416/aarForImage.zip)

note that i only checked it with godot 4.1.1

**Comment by Ayomideabdulazeez** [comment]
> Hi @yan88a @Ayomideabdulazeez @blurrred , could you guys please share an .aar file that works in godot 3.5.3? I've tried to generate it myself with the solutions you provided but always get a gradle error. I'd really appreciate it, thanks.

Hello, what error do you receive?

**Comment by bouncymarble** [comment]
Thank you @yan88a , unfortunately I was only able to export the app, had to increase Min SDK to 24 to fix a build error, but the plugin won't load while debugging.

@Ayomideabdulazeez 
> Hello, what error do you receive?

"Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.1.16.". I fixed that one but then, "Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.". Same error with other gradle versions, so idk what I'm doing wrong.

**Comment by yan88a** [comment]
@bouncymarble - try it with this gdap.
note that it only has 1 function -->
getGalleryImage()
you should get a dic with the selected img on signal "image_request_completed"
[Image.zip](https://github.com/Lamelynx/GodotGetImagePlugin-Android/files/12822288/Image.zip)

**Comment by bouncymarble** [comment]
@yan88a Thank you, it loaded and getGalleryImage() now opens the gallery, but when I pick an image it doesn't return anything. I connected the signal "image_request_completed" but it's not triggering, cmd prints this:

Call - getGalleryImage
result is -1
fired signal

Btw, shouldn't you rename the plugin? maybe it's overriding the godot class with the same name "Image", and might be causing the error "Invalid call. Nonexistent function 'new' in base 'JNISingleton'", just another theory because now I get this error "Invalid call. Nonexistent function 'setOptions' in base 'JNISingleton'." which makes sense in this case. So maybe if you rename it to "GodotGetImage" it'll fix the Image.new() issue.

Is there a way to set the image parameters like we used to with setOptions()? I need to set image_height, image_width, keep_aspect, image_quality and image_format to avoid memory issues and unsupported image extensions.

**Comment by yan88a** [comment]
well,
it wont have any abilities to set anything :)
just added the getimage function (that was my needed functionality)
in my case- with godot 4.1.2 it does return a dict (by the way - the intent result code is -1 --> like in your case)

as for the nonexistant function - in your case - its really not implemented in the plugin.. 

in mine - i do think its an issue with the gradle config, will play with it.. if by some miracle i'll manage to make it work - i'll share the aar & gdip here...

**Comment by yan88a** [comment]
@bouncymarble  - you are a wizard.
it was the name confusing it..
in any case - here is the aar & its gdap
[Picker.zip](https://github.com/Lamelynx/GodotGetImagePlugin-Android/files/12824947/Picker.zip)
basically it only has 1 function and 1 signal:
getGalleryImage()

image_request_completed - note that it return's a dictionary with 1 key (the pic..)

thanks man,

hope it will help you as well :)

**Comment by yan88a** [comment]
@bouncymarble - you managed to get an image and parse it in the editor?
most images return in an array (some return as null)

**Comment by bouncymarble** [comment]
@yan88a I confirmed your plugin is incompatible with godot 3.5.3 because the way of connecting signals changed in godot 4. `picker.connect("image_request_completed", self, "_on_image_request_completed")` doesn't work, it has to be `picker.image_request_completed.connect(_on_image_request_completed)`. I just did a test in godot 4.1.2 and it returns the dictionary as expected. So I guess I'll keep struggling with android studio. Thanks for your help anyway :)

**Comment by yan88a** [comment]
Ummm
I think it's because I exported it with 4.1.2 templates
If you want, I can export it with whatever you need later tonight
Should be pretty easy..

**Comment by bouncymarble** [comment]
@yan88a Yeah I'm trying to export it with the library "godot-lib.3.5.3.stable.release.aar", but maybe you could zip your project folder (android studio), so I can adapt it to my needs, plus I really want to learn how to export a plugin. Sorry for bothering you 😅

**Comment by yan88a** [comment]
Sure, no problem.

**Comment by yan88a** [comment]
@bouncymarble - so - 
here is an exported aar with 3.5 template - 
[aarFile.zip](https://github.com/Lamelynx/GodotGetImagePlugin-Android/files/12834252/aarFile.zip)
and the project zip - 
[picker.zip](https://github.com/Lamelynx/GodotGetImagePlugin-Android/files/12834259/picker.zip)
couldnt zip it with the godot lib - place it into picker/app/libs and rename to godotLib.aar - than make sure to sync the gradle.

in any case - my masters degree in android plugins was by @finepointcgi ...
here is his youtube video on that - he really did an amazing job
https://youtu.be/kwf8SFfH4s8?si=SiTxpCxJisKAiGLp


now - if you managed to get the array into the editor from the plugin - let me know if you managed to convert it in the editor to a picture.. still having some difficulties with that.

and id anyone here has a lead on ios plugins creation - that would be an early Christmas for me :)

**Comment by bouncymarble** [comment]
@yan88a Finally! I was able to export it with your folder. The library for godot 4 actually works in 3.5 as well, I forgot to remove the setOptions line, so it was not reaching the signal connection..

I modified your code to resize the image, otherwise it takes too long to load, and I only need 512x512. Here's the code in case you want to set a fixed size:

```
    @Override
    public void onMainActivityResult(int requestCode, int resultCode, Intent data) {
        Log.d("godot","result is "+ resultCode);
        if (resultCode == RESULT_OK) {
            // Get the URI of the selected media file
            Uri imageUri = data.getData();
            Bitmap bitmap;
            try {
                InputStream imageStream = getGodot().getContext().getContentResolver().openInputStream(imageUri);
                bitmap = BitmapFactory.decodeStream(imageStream);
                bitmap = getResizedBitmap(bitmap, 512);
                imageStream.close();
            } catch (FileNotFoundException e) {
                throw new RuntimeException(e);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
            Dictionary imageDict = new Dictionary();
            ByteArrayOutputStream stream = new ByteArrayOutputStream();
            bitmap.compress(Bitmap.CompressFormat.JPEG, 90, stream);
            try {
                stream.close();
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
            imageDict.put("0", stream.toByteArray());
            Log.d("godot","fired signal");
            emitSignal("image_request_completed", imageDict);
        }
    }

    public Bitmap getResizedBitmap(Bitmap image, int maxSize) {
        int width = image.getWidth();
        int height = image.getHeight();

        float bitmapRatio = (float)width / (float) height;
        if (bitmapRatio > 1) {
            width = maxSize;
            height = (int) (width / bitmapRatio);
        } else {
            height = maxSize;
            width = (int) (height * bitmapRatio);
        }
        return Bitmap.createScaledBitmap(image, width, height, true);
    }
```

And this is how I convert the dictionary to an image/texture:

```
func _on_image_request_completed(dict):
	for img_buffer in dict.values():
		var image = Image.new()
		var error = image.load_jpg_from_buffer(img_buffer)
		if error != OK:
			error = image.load_png_from_buffer(img_buffer)
		if error == OK:
			marble_editor.image_imported(image)

func image_imported(image):
	# must wait a frame, otherwise the texture is black
	yield(get_tree(), "idle_frame")
	var texture = ImageTexture.new()
	texture.create_from_image(image, 0)
	marble.get_node("CollisionPolygon2D/Sprite").texture = texture
```

Hope it helps, in my app it seems to work as before (tested on android 13, 10 and 9). Thank you so much, you're a lifesaver!

> in any case - my masters degree in android plugins was by @finepointcgi ...

lol I also watched his video but for some reason I get a lot of errors when compiling or exporting my plugins.

> and id anyone here has a lead on ios plugins creation - that would be an early Christmas for me :)

No idea tbh. I'm using this https://github.com/godotengine/godot-ios-plugins for PhotoPicker, InAppStore and GameCenter. It has more features but idk if they will update it for godot 4.

**Comment by djordjije** [comment]
I have been following this for a while. @yan88a congratulations on making your own! 
So, is there no way to get a single image from Android with a Godot 4 template currently?
I am looking for the ability to get a single image from both Android and iOS with Godot 4. 
I don't mind making my own aar file. But would that even work? I am new to Godot and sorry if I am not phrasing it properly.

**Comment by Lamelynx** [comment]
This issue should have been resolved.
Plugin is from now on only supported by Godot 4.2+ due to plugin architecture version 1 is deprecated.
