### ISSUE TITLE
android 12 not work

### ISSUE THREAD

**Issue by zedrun00** [Lamelynx/GodotGetImagePlugin-Android#17]
android 12 not request READ_MEDIA_IMAGES.
![image](https://github.com/Lamelynx/GodotGetImagePlugin-Android/assets/104408400/a6b56429-659f-434a-bea3-9e77de16f5c2)

but android 13 is normal.
![image](https://github.com/Lamelynx/GodotGetImagePlugin-Android/assets/104408400/4529741a-dee7-4058-a681-f1ad4f65706c)

**Comment by Lamelynx** [comment]
In android 13 the permission is changed. READ_MEDIA_IMGES is not used below android 13. 
See the source [GodotGetImage.tk line 181](https://github.com/Lamelynx/GodotGetImagePlugin-Android/blob/d4b06f7b8bb8c1f5af968d37120706330cd7fd3f/plugin/src/main/java/com/gmail/lamelynx/godotgetimage/GodotGetImage.kt#L181)

Please add some more context on the issue, what happens when you run your code etc.

**Comment by zedrun00** [comment]
[android_get_image.zip](https://github.com/Lamelynx/GodotGetImagePlugin-Android/files/15248948/android_get_image.zip)
[video.zip](https://github.com/Lamelynx/GodotGetImagePlugin-Android/files/15249046/video.zip)

**Comment by Lamelynx** [comment]
I have not tested your code but in the function `_on_button_pressed()` try to remove the line `image_plugin.resendPermission()`.

Have you tried the demo project? It does work with Android 12.

**Comment by zedrun00** [comment]
> I have not tested your code but in the function _on_button_pressed() try to remove the line image_plugin.resendPermission().   

my old code not has line `image_plugin.resendPermission()`,  but also not work .

> Have you tried the demo project? It does work with Android 12.  

what project you mean? [this project?](https://github.com/Lamelynx/GodotGetImagePlugin-Android/files/15248948/android_get_image.zip) or has official project?

**Comment by Lamelynx** [comment]
I mean this project: [plugin/demo](https://github.com/Lamelynx/GodotGetImagePlugin-Android/tree/d4b06f7b8bb8c1f5af968d37120706330cd7fd3f/plugin/demo).
The demo project work on my android 12 phone.
