### ISSUE TITLE
Demo project showing Could not load plugin ?

### ISSUE THREAD

**Issue by pyrovoice** [Lamelynx/GodotGetImagePlugin-Android#18]
Hello, I got the demo project after failing to make it work in my project, but the demo also shows that the plugin is not loading correctly there. Is there additional steps to be doing after unpacking the release to addons and enabling it in Godot? Thanks
Godot version 4.2.1

**Comment by Lamelynx** [comment]
Hi, you need to either rebuild the plugin for your Godot version or use Godot 4.2.0.

**Comment by pyrovoice** [comment]
Building for 4.2.1.stable or running the demo on 4.2 stable releases also do not work

**Comment by Lamelynx** [comment]
What device are you running the project on?
Do you have an ADB output?

**Comment by pyrovoice** [comment]
windows, no ADB output

**Comment by Lamelynx** [comment]
The plugin won't load on anything besides android.
You need to run you app on your android phone.
