### ISSUE TITLE
Png file transparency turns to black

### ISSUE THREAD

**Issue by salvafide** [Lamelynx/GodotGetImagePlugin-Android#2]
Hey Lamelynx, I got your plugin incorporated into my game. I saw your post back here https://godotengine.org/qa/78664/black-texture-when-loading-images-in-runtime-on-android. I am able to load a texture, but all the transparency values are turning to black. I tried to switch load_jpg_from_buffer to load_png_from_buffer but that gives me an error that the file is not a png. Have you figured out how to load an image and keep its transparency? JPG doesn't support transparency.

**Comment by Lamelynx** [comment]
Hi
I have added additional option "image_format". Set this to "png" and then use load_png_from_buffer and you should be good to go!
See release version 0.1.1

**Comment by salvafide** [comment]
I copied over your example project, then uncommented the 2 lines for the png code, but I still get the same error complaining that its is not a png file

![Error](https://user-images.githubusercontent.com/10732357/96089628-f76fd600-0e7b-11eb-9276-c4d8c3f3f105.png)

Does this work on your phone? Am I doing something wrong?

**Comment by Lamelynx** [comment]
It's works for me. In the example project you need to push "100x100..." button to set the png option.

**Comment by salvafide** [comment]
I cannot tell what the "set image to 100*100 but keep aspect ratio button is doing"? But the png images I am loading are still losing their transparency.

![image](https://user-images.githubusercontent.com/10732357/96092025-28053f00-0e7f-11eb-9e7a-031617901552.png)

Im getting the image on the right when I use 'load_jpg_..", and that error when loading with "load_png..", I want the image on the left

**Comment by salvafide** [comment]
Apologies,(its a little late for me here) It is working. I just was doing it wrong, now I get what you were saying. Gotta press that button first, then load png. I appreciate the fast responses.

**Comment by Lamelynx** [comment]
Great :-)
