### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by salvafide** [Lamelynx/GodotGetImagePlugin-Android#3]
Was wondering if you have learned how to store this image, i.e save it into the game so that image can be loaded when the game is closed and started again?
Another idea is if you can gain access to the path var, store the path when saving, and use this to load the images again at runtime?

**Comment by Lamelynx** [comment]
[Check this](https://docs.godotengine.org/en/stable/classes/class_image.html#class-image-method-save-png)
This may work:
```
image.save_png("user://path/filename")
```

**Comment by salvafide** [comment]
So on first start of the game I create a directory, no error, load an image, save_png("user://newDir/ImageName.png)" no error
But when I try to then grab it I am running into trouble,  $TextureRect.texture = load(path to img) does not work, neither does $TextureRect.texture = path. I think load should work, but do you see something I am missing?

**Comment by salvafide** [comment]
Nevermind, got it, had to turn it into a texture from image, thanks
