### ISSUE TITLE
3.2.4 Support

### ISSUE THREAD

**Issue by Algorithmus** [Lamelynx/GodotGetImagePlugin-Android#4]
I know it's not in stable at this point, but trying to build it with the godot-lib 3.2.4 aar doesn't work. I'm not an Android developer though, so I'm not sure if my code is correct, but here's what I had to do to make it work, at least for the gallery images:

https://gist.github.com/Algorithmus/933e86718fdc735462ccd04e8d764173

Hope it will be useful when you get around to adding 3.2.4 support when it is stable.

**Comment by Lamelynx** [comment]
Thanks for your contribution. Will look into this when 3.2.4 is released.

**Comment by clemens-tolboom** [comment]
Now we have a stable 3.3 released April 21, 2021 ;-)

**Comment by Lamelynx** [comment]
Thanks for the reminder :-) I have now updated the plugin for 3.3
